name: "CI for PRs"

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

concurrency:
  group: '${{ github.head_ref || github.run_id }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  format-build-test-backend:
    name: "Format & Build & Test (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.405
      - name: "Restore dependencies"
        run: dotnet restore
      - name: "Format"
        run: dotnet format --severity info -v diag --verify-no-changes
      - name: "Build"
        run: dotnet build --no-restore --configuration Release -v m
      - name: "Test"
        run: dotnet test --no-build --no-restore --configuration Release -v n